image: proboci/ubuntu-14.04-lamp:php5.6-nightly
assets:     
  - d8testsite.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    database: d8testsite.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: true
    clearCaches: true
