assets:
  - dev.sql.gz
steps:
  - name: Probo CI site setup
    plugin: Drupal
    database: dev.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: true
    clearCaches: true